### ISSUE TITLE
HOW TO DOWNLOAD OLD COMMIT OF THIS PROGECT?!

### ISSUE THREAD

**Issue by sashapzzx** [efidroid/projectmanagement#159]
How to do this
repo checkout checkout 408945416b0e195077ad48ba468c8e8e65392956
error: project 408945416b0e195077ad48ba468c8e8e65392956 not found

**Comment by feherneoh** [comment]
I cannot see what your problem is. You messed up the command arguments, so you get an error. Also you used fullcaps in the issue title and expect help.

**Comment by M1cha** [comment]
@sashapzzx can you show us the exact command you used?
Generally, checking out an old revision works by using an old revision of the manifest repository
https://source.android.com/setup/develop/repo#init

You'll also have to revert some repos to older version because the manifest points to master branches instead of tags.

**Comment by feherneoh** [comment]
> @sashapzzx can you show us the exact command you used?
> Generally, checking out an old revision works by using an old revision of the manifest repository
> https://source.android.com/setup/develop/repo#init
> 
> You'll also have to revert some repos to older versions because the manifest points to master branches instead of tags.

I'm pretty sure he used what he posted, that is one with "checkout checkout"

**Comment by M1cha** [comment]
you're right I missed that.
btw, I made the old lk code compile again: https://github.com/efidroid/manifest/tree/master-legacy
