### ISSUE TITLE
Change recovery in the app

### ISSUE THREAD

**Issue by z3ntu** [efidroid/projectmanagement#69]
It would be nice if there was a graphical way to just swap the recovery.img instead of changing the file `/sdcard/UEFIESP/partition_recovery.img` (but this also works)

Also somehow related to #21

**Comment by feherneoh** [comment]
You can just flash a new recovery.img from TWRP, that will overwrite that file (unless recovery is booted unpatched)

**Comment by M1cha** [comment]
yes as feh said and as I already told you, you can use any recovery installer in Android, update.zip in Recovery or 'dd' from the console to flash to the virtual partition - as long as you're using patched boot.

If I don't explain a concept to users it's usually because EFIDroid handles everything and the user really doesn't have to know about it.
