### ISSUE TITLE
Settings app crashes in Fairphone OS

### ISSUE THREAD

**Issue by z3ntu** [efidroid/projectmanagement#75]
I didn't try it myself but a person using efidroid on his Fairphone experienced this issue when using Fairphone OS as a secondary ROM. Fairphone OS download links if you want: https://fairphone.zendesk.com/hc/en-us/articles/213290023-Fairphone-OS-downloads-for-Fairphone-2

**Comment by M1cha** [comment]
this report needs a logcat to be of any use.

**Comment by arne-claeys** [comment]
I have encountered the same issue.
As soon as I try to open the system settings in Fairphone Open OS (my secondary system) it crashes immediately.
In my case it seems to be caused by a NullPointerException in android.security.IKeystoreService.exist.
When I enable the PIN code on my lock screen, the same error leads to a crash of SystemUI. Once upon a few reboots I don't have this problem.
A second problem I have is that I can only run my secondary OS in SELinux permissive mode.

--------- beginning of crash
E/AndroidRuntime( 1473): FATAL EXCEPTION: main
E/AndroidRuntime( 1473): Process: com.android.systemui, PID: 1473
E/AndroidRuntime( 1473): java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.zero()' on a null object reference
E/AndroidRuntime( 1473): 	at android.os.Parcel.readException(Parcel.java:1552)
E/AndroidRuntime( 1473): 	at android.os.Parcel.readException(Parcel.java:1499)
E/AndroidRuntime( 1473): 	at com.android.internal.widget.ILockSettings$Stub$Proxy.checkPassword(ILockSettings.java:402)
E/AndroidRuntime( 1473): 	at com.android.internal.widget.LockPatternUtils.checkPassword(LockPatternUtils.java:331)
E/AndroidRuntime( 1473): 	at com.android.keyguard.KeyguardAbsKeyInputView.verifyPasswordAndUnlock(KeyguardAbsKeyInputView.java:110)
E/AndroidRuntime( 1473): 	at com.android.keyguard.KeyguardPinBasedInputView$2.onClick(KeyguardPinBasedInputView.java:162)
E/AndroidRuntime( 1473): 	at android.view.View.performClick(View.java:4781)
E/AndroidRuntime( 1473): 	at android.view.View$PerformClick.run(View.java:19874)
E/AndroidRuntime( 1473): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 1473): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1473): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1473): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 1473): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1473): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1473): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 1473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 1473): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by arne-claeys** [comment]
Also while starting the Network Management Service a NullPointerException occurs in android.security.IKeystoreService.exist

F/SystemServer( 1211): BOOT FAILURE making Network Managment Service ready
F/SystemServer( 1211): java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.exist(java.lang.String, int)' on a null object reference
F/SystemServer( 1211): 	at android.security.KeyStore.contains(KeyStore.java:137)
F/SystemServer( 1211): 	at android.security.KeyStore.contains(KeyStore.java:145)
F/SystemServer( 1211): 	at com.android.server.net.LockdownVpnTracker.isEnabled(LockdownVpnTracker.java:88)
F/SystemServer( 1211): 	at com.android.server.NetworkManagementService.prepareNativeDaemon(NetworkManagementService.java:566)
F/SystemServer( 1211): 	at com.android.server.NetworkManagementService.systemReady(NetworkManagementService.java:298)
F/SystemServer( 1211): 	at com.android.server.SystemServer$2.run(SystemServer.java:1160)
F/SystemServer( 1211): 	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:11354)
F/SystemServer( 1211): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1128)
F/SystemServer( 1211): 	at com.android.server.SystemServer.run(SystemServer.java:265)
F/SystemServer( 1211): 	at com.android.server.SystemServer.main(SystemServer.java:179)
F/SystemServer( 1211): 	at java.lang.reflect.Method.invoke(Native Method)
F/SystemServer( 1211): 	at java.lang.reflect.Method.invoke(Method.java:372)
F/SystemServer( 1211): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
F/SystemServer( 1211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
F/SystemServer( 1211): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by z3ntu** [comment]
@arne-claeys thanks for the stracktrace 👍

**Comment by arne-claeys** [comment]
This should be another useful error in my log.

`E/QCOMKeyMaster(  328): Keymaster app not loaded: Max attempts reached
E/keystore(  328): could not open keymaster device in keystore (Operation not permitted)
E/keystore(  328): keystore keymaster could not be initialized; exiting`

This error is logged by /system/bin/keymaster after it calls /vendor/lib/libQSEEComAPI.so
QSEEComAPI doesn't write anything to the log.

It is quite mysterious why one time everything works and sometimes after a reboot keymaster fails to load. There doesn't seem to be an exact way to reproduce the error.

The cause seems to be different from this post: http://stackoverflow.com/questions/14895307/android-loading-keymaster-error. Even when the keystore loads fine, the permissions of /firmware/image/keymaste.mdt are r--.
Does anyone know what cause this?

**Comment by M1cha** [comment]
the app will go away.
