### ISSUE TITLE
Nexus 6P Support

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#83]
ARCH: MSM8994
OEM: Huawei
Branch used to build: LA.BF64

Whether booted or flashed to the Boot partition, LK doesn't initialize, and it hangs at the Google (aboot) logo. No LK access over USB.

This is likely due to the looming "LK doesn't boot on 64-bit devices" we don't understand yet.

**Comment by M1cha** [comment]
I always assumed the problem lies within the BR/HB branches - especially because I have a fully working 8992 device here(mi4c).

Is it possible that the bootloader used by LG is a problem?
Maybe it fails/denies to boot but doesn't show error messages and doesn't even reboot.
Or it forces booting in 64bit mode?

I'd say try sideloading the stock bootloader but I haven't even been able to do that on mi4c and I have no idea why it doesn't work.

**Comment by npjohnson** [comment]
@M1cha LG? This is Huawei. And doesn't msm8994 use LA.BF64? Not BR/HB?

**Comment by M1cha** [comment]
"LG? This is Huawei." sounds like I mixed sth. up, sry.

"And doesn't msm8994 use LA.BF64? Not BR/HB?" That's why I said I though BR/HB are the problem. msm8994 uses LA.BF64 and I didn't expect this problem to happen.

what you can try on all your devices with this problem is changing  the LK loading addr to the same as used by the stock bootloader(and rm -Rf out after doing so). Many devices don't like booting LK from the initial linux loading addr.

**Comment by npjohnson** [comment]
By using @M1cha's manual FDT appendage method, we are able to boot LK!

It still visually hangs at the Google logo, but now we have fastboot access behind it!

I figured I'd try 2NDSTAGE_DTB, and that resulted in the display briefly firing on, and then running a ton of text in front of tux then rebooting. Not sure how to debug such a quick reboot.

**Comment by M1cha** [comment]
in 90% of all cases people need DEFINES += WITH_2NDSTAGE_DISPLAY_DMA_TRIGGER and not 2NDSTAGE_DTB. 2NDSTAGE_DTB just auto detects if u have a cmd-panel with vsync requirements and enables that functionality automatically.

So, if you got a cmd panel, go back to the normal driver and use the trigger flag.

**Comment by npjohnson** [comment]
@M1cha That did it!

**Comment by npjohnson** [comment]
No progress this week.

**Comment by npjohnson** [comment]
I tired a ton of things to get UEFI to boot on the device, but no dice. :/

**Comment by computer777** [comment]
@npjohnson hey, just curious if there's any progress for the nexus 6p.
