### ISSUE TITLE
LK doesn't boot on /most/ 64-bit devices

### ISSUE THREAD

**Issue by npjohnson** [efidroid/projectmanagement#89]
As the title states.

We believe it may be due to the stock bootloaders forcing 64-bit boot modes, but have no definitive proof yet.

So far, it doesn't boot on:

- HTC One M9 (msm8994, FDT): Stuck on aboot splash screen
- Huawei Nexus 6P (msm8994, FDT):  Stuck on aboot splash screen
- LG Nexus 5X (msm8992, FDT):  Stuck on aboot splash screen
- Google (HTC) Pixel/Pixel XL (msm8996, FDT):  Stuck on aboot splash screen
- LG G5 (msm8994, FDT): someone in the chat tried it iirc, and they said stuck on aboot splash screen
- LeEco Le Max 2 (msm8996, FDT): reboot
- ZTE Axon 7 (msm8996, FDT): reboot/powerdown
- Oneplus 3/3t (msm8996, FDT): stuck
- Lenovo ZUK Z2(msm8996, FDT): 900E diag mode
- Xperia X Compact (msm8956, FDT): stuck

**Comment by M1cha** [comment]
do what I suggested in the 6p issue:

"what you can try on all your devices with this problem is changing the LK loading addr to the same as used by the stock bootloader(and rm -Rf out after doing so). Many devices don't like booting LK from the initial linux loading addr."

**Comment by Glove007** [comment]
How exactly can we do that?

**Comment by M1cha** [comment]
dump the 'aboot' partition and run binwalk on the resulting file

**Comment by Glove007** [comment]
Where can I change the LK loading addr? In config.ini under LK_BASE or BOOTIMG_BASE? And should I use the kernel addr or the ramdisk addr?

Thanks for your help!

**Comment by M1cha** [comment]
LK_BASE. kernel/ramdisk address? sounds like you're looking in the wrong place because these have nothing to do with this.

Maybe u dumped the boot partition by accident? 'aboot' is not a typo.

**Comment by Glove007** [comment]
What is it then?
Sorry that I don't understand so much…

**Comment by Glove007** [comment]
I dumped /dev/block/bootdevice/by-name/aboot

**Comment by M1cha** [comment]
that's correct but there are no kernel or ramdisk addresses. if you're unusre, just upload the binary and I'll take a look.

**Comment by Glove007** [comment]
Here is it: [https://drive.google.com/open?id=0B1kUxbPpOiT9TE9NVlE4WU1CTm8](https://drive.google.com/open?id=0B1kUxbPpOiT9TE9NVlE4WU1CTm8)

Thank you!

**Comment by M1cha** [comment]
@Glove007 0x91800000

**Comment by M1cha** [comment]
I've added LeEco Le Max 2 (msm8996) to the list. changing the loading addr didn't help and the device force reboots which usually is a sign of the hypervisor forcing a reboot.

**Comment by twoeye** [comment]
ZTE/Axon 7 (msm8996)

With adjusted LK_BASE from aboot: fastboot lk reboots phone.
Without adjusted base: fastboot lk turns off phone.

**Comment by M1cha** [comment]
ok two more ideas/information requests:
- does lk_origdtb.img work on these devices?
- do these devices use dt.img or appended fdt?

**Comment by npjohnson** [comment]
@M1cha 

- No, lk_origdtb makes no difference, still hangs at the aboot splash screen of most the respective devices.
- According to EFI Droid, they use appended FDT, but I might have had an idea that may be the root of this whole issue... I am almost certain the Nexus 6P, Pixel XL, and HTC One M9 all use DT (and not FDT). Is there a simple way to check this? I was wondering if maybe some mis-handling by EFI Droid's unmkbootimg of the device tree creation.

**Comment by M1cha** [comment]
@npjohnson if unpackbootimg aid there is an fdt, then that should be true. Otherwise the dtb patching would fail due to invalid contents.
Also Nexus devices used appended fdt's long before qcom so I'm pretty sure the 6p does too.
You can double-check if EFIDroid is right but looking at your ROM's BoardConfig.mk but if BOOTIMG_FDT is defined in EFIDroid and there's an valid fdt in the device directory your device is certainly using fdt.

**Comment by npjohnson** [comment]
@M1cha That FDT define (nor any other FDT define) is made anywhere in these devices device trees (in AOSP). The output image type is however, defined as zImage-dtb, does that give you any clues? How do I tell if the EFI Droid unpacked FDT images are valid?

**Comment by M1cha** [comment]
@npjohnson the define I've mentioned is an EFIDroid define, not an Android one.
https://github.com/LineageOS/android_device_huawei_angler/blob/cm-14.1/BoardConfig.mk#L35
Image.gz-dtb is means: 'cat Image.gz dtb1.dtb dtb2.dtb ...' with Image.gz being a NON-self decompressable Image.
the 32bit equivalent of this is zImage-dtb which mean 'cat zImage dtb1.dtb dtb2.dtb ...' with zImage being a self-decompressable Image.

with that being said, the following possible causes come to my mind:
- the stock bootloader doesn't like 32bit kernels for some reason
- the stockbl doesn't like this header(but it should since linux uses the same): https://github.com/efidroid/build/blob/master/core/tasks/lk.sh#L134

if 32bit is the reason we're screwed because I don't know if we can pull coding stable 32bit lk and UEFI that easily.

**Comment by npjohnson** [comment]
@M1cha Ah. I see your point.

A way I could test this quickly is to build a 32 bit kernel off the devices kernel source and see if I could boot it right?

**Comment by M1cha** [comment]
@npjohnson if that's supported yes, I dunno if you can easily build one or if it requires some more porting efforts.

**Comment by npjohnson** [comment]
@M1cha I know offhand that none of Angler's firmware's are 64-bit, and it /shouldn't/ be too much effort. I'll see what I can do tomorrow.

**Comment by M1cha** [comment]
@npjohnson I've started editing the OP to add info about what happens after booting lk(reboot/shutdown/stuck). can you do that for your devices too?

**Comment by npjohnson** [comment]
@M1cha done

**Comment by M1cha** [comment]
@npjohnson thx. did you ever check if they device is really stuck or if it enters qcom download mode?

**Comment by npjohnson** [comment]
@M1cha Stuck, no USB interface.

**Comment by M1cha** [comment]
@npjohnson can you extend the list with FDT/DT information like I did with ZUK Z2?
If all of them use FDT then we have our reason. my xiaomi mi2 has an msm8992 and works, but uses a DT.

**Comment by npjohnson** [comment]
@M1cha They're all FDT :)

Think we found the problem then.

**Comment by drsn0w** [comment]
Stuck at Google splash screen on Nexus 5X (bullhead)

**Comment by npjohnson** [comment]
@drsn0w added to the list

**Comment by M1cha** [comment]
try to do this (after compiling):
```
cat out/device/?/?/lk_kernel/build-?/lk.bin | gzip -n -f -9 > out/lk.bin.gz
cat out/lk.bin.gz device/?/?/fdt.img > out/Image.gz-dtb
```

then, repack lk.img with out/Image.gz-dtb as the kernel. Since the build system prints the mkbootimg command at the end you just have to copy and edit it.
Pleas not that even if this works it's not a permanent solution for many devices because fdt and/or gzip-compressed kernel were not supported on the bootloader which the device was shipped with.

**Comment by oshmoun** [comment]
Xperia X Compact (kugo) also seems to have the same issue.
i.e, booting lk.img or lk_origdtb.img results in a stuck device with no usb connection

**Comment by drsn0w** [comment]
@M1cha I tried your suggested fix on Nexus 5X (bullhead)
I was able to boot into the first LK step, and run `finalize_device`. Currently doing more testing, will update.

**Comment by npjohnson** [comment]
@M1cha using that repack method on the Nexus 6P results in being able to boot LK!!! I was able to finalize_device and all.

It still visually hangs at the Google logo, but now we have fastboot access behind it!

I figured I'd try 2NDSTAGE_DTB, and that resulted in the display briefly firing on, and then running a ton of text in front of tux then rebooting. I'll move that to the 6P issue though. Looks like we found the root of this issue!

**Comment by drsn0w** [comment]
@npjohnson take a look in #porting on Slack, we're working through some display issues on the 5X, might be similar for 6P

**Comment by drsn0w** [comment]
5X LK boots with working display, but when I did the same to the UEFI kernel it simply reboots into system

**Comment by titanlts** [comment]
Same bug causing device to boot to the system instead of staying in lk.img . Looking for a resolve soon 

Trying to port to Moto G 2014 (msm8226)

**Comment by npjohnson** [comment]
@titanlts That'd be incorrect. 8226 is not 64 bit. Plus, the Moto G 2014 already has a fully functional port (only thea officially, but just switching the name gets titan to work, and merlin requires a few tiny edits).

**Comment by titanlts** [comment]
Yes ! I already know that titan is a arm not arm64 . But guys on XDA , told
me to just drop the info about my device if it had something related to
this issue .Thanks for that info ! I will look into that and change it ;)

**Comment by titanlts** [comment]
@npjohnson Can you help guiding me to the lk.img and uefi_boot.img of thea . So that i can modify it to make it work on titan

**Comment by npjohnson** [comment]
@titanlts

It's a tad more complicated.

Send me your boot.img and I'll remake the device tree and submit for official support through @M1cha.

**Comment by titanlts** [comment]
@npjohnson No need :) . I managed to build it successfully . It's working now

**Comment by titanlts** [comment]
Except for the uefi_boot.img . it is freezed in the Splashscreen

**Comment by twoeye** [comment]
ZTE Axon 7

lk_origdtb.img: Reboots device
Image.gz-dtb/repacked lk.img: Reboots device

I'm fairly confident in my results, however this is at a technical level which is a bit unfamiliar.

**Comment by npjohnson** [comment]
@titanlts Offer still stands. Email your boot image to the email on my GitHub profile and I'll submit for official support, as I had finished it, but just forgot to submit, super easy to recreate though.

**Comment by andr68rus** [comment]
Hello! Any progress with msm8996?

**Comment by M1cha** [comment]
msm8996 has another GIC(v3) maybe that's the problem?

**Comment by Nobiscum** [comment]
Does anybody knows which branch from codeaurora for LK is actual? I need to compile LK for OnePlus3

**Comment by Adipatiarya** [comment]
how to dump adress base aboot

**Comment by JTRealms** [comment]
I tried to disassemble the aboot image from my OnePlus3t in IDA, my goal was to check if `ABOOT_FORCE_KERNEL64_ADDR`is set, my assumption is that stops loading of efidroids 32bit LK.

The "aboot" image is in qualcomm MBN format, normally aboot's first 40 btyes are a ELF header containing aboots sizes and addresses, but isnt the case here.

So, in addition to the above question, does anyone know how to obtain the "ImgBase" value from these MBN files? without it, aboot cannot be disassembled correctly.

**Comment by M1cha** [comment]
@JTRealms this is the format of the header: https://github.com/efidroid/modules_libboot/blob/master/loaders/qcmbn.c#L31

Also, there are plugins for IDAPro to load mbn files.

**Comment by fxsheep** [comment]
@M1cha @npjohnson I have the same problem on Readmi 3S (land) , both lk and uefi stuck at aboot screen.I'm not very familiar with ARM or Qualcomm, but here are some of my ideas:

Ater some investigations I think it isn't because stock LK forces AArch64 boot mode.All of these devices shares a similar lk codebase, some even have arm32 kernel, so why should it do?
So I did some experiments:
1.Boot an arm32 kernel (my device has arm64 stock kernel and rom).I didn't try to port my own, instead I tried a kernel from a very similar device with arm32 kernel, Redmi S2.(Ignore the fact that it has msm8953 while mine is msm8937).
   It rebooted immmediately (of course), but from pstore kmesg I have seen it booting (but crashed because 8937 and 8953 difference, ofc). This has proved that my LK in fact has the ability to boot arm32 images.
2.Some facts: I found that the difference between arm32 and arm64 boot.img is that arm32 has a zImage with a special header while arm64 is Image.gz+dtbs.Stock LK probably uses this fact to determine 32/64 bootmodes, and EFIDroid matches arm32 perfectly.
3.Later I had a good idea: Maybe the LK has been running but just crashed before fastboot?Why not get some UART logs?However it isn't convenient for me to get the UART connection to the SoC so I went another way: https://github.com/efidroid/bootloader_lk/blob/91bd0e0878af6b6731986519387d17c411482d34/platform/msm_shared/debug.c#L67
LK has put the UART log buffer to memory.Although it isnt hardcoded but it looks quite static.Based on the fact that my device has a pretty open EDL, I went to dump the buffer directly in EDL mode:
https://github.com/alephsecurity/firehorse
This is a great tool for hacking the EDL (yay).
With this tool I dumped randomly starting from 0x80008000 which is the default NOUEFI LK loadaddr.
Soon I found the buffer is located at 0x80073E58.(since it has RLOG magic it is quite outstanding)

PS H:\下载\firehorse-master\host> C:\python27-x64\python.exe firehorse.py -c COM3 -t nokia6 fw peek 80073E58 400
INFO: 80073e58  52 4c 4f 47 00 40 00 00 2b 00 00 00 2b 00 00 00   RLOG.@..+...+...
80073e68  44 2f 5b 30 5d 20 73 6d 65 6d 20 72 61 6d 20 70   D/[0] smem ram p
80073e78  74 61 62 6c 65 20 66 6f 75 6e 64 3a 20 76 65 72   table found: ver
80073e88  3a 20 31 20 6c 65 6e 3a 20 35 0a 00 00 00 00 00   : 1 len: 5......
80073e98  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
80073ea8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
80073eb8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
80073ec8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
80073ed8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
Whoops! It printed only one line about smem ,and dies after that? At least the LK is really booting and "the reboot" isn't really caused by HYP.I'm looking into LK boot sequnce to find out why.

**Comment by fxsheep** [comment]
And a weird problem occurs, my device isn't able to poweroff itself after booting that LK! Poweroff=reboot, maybe something about PMIC is messed up.

**Comment by fxsheep** [comment]
After a lot of debugging I found the following problems:
1.Platform id check presents, e.g.
https://github.com/efidroid/bootloader_lk/blob/qcom/LA.BR/target/init.c#L248
I removed all of them.
2.Turning on ARM cache (by default) will stuck the device.So remove it too.
https://github.com/efidroid/bootloader_lk/blob/91bd0e0878af6b6731986519387d17c411482d34/arch/arm/arch.c#L54
Now it looks like this:

D/[0] hello smem_ram_ptable_init_v1
D/[0] smem ram ptable found: ver: 1 len: 5
D/[0] hello platform_init_mmu_mappings
D/[0] hello platform_init_mmu_mappings pass
D/[0] hello arm_write_ttbr pass
D/[0] hello arm_write_dacr pass
D/[0] hello arm_write_cr1 /* turn on the mmu */ pass
D/[0] hello arm_mmu_init pass
D/[0] hello arch_enable_cache pass
D/[0] hello ARM_WITH_NEON pass
D/[0] hello ARM_CPU_CORTEX_A8 pass
E/[0] boardinfo reached!
D/[0] hello board_get_ddr_subtype
D/[0] hello smem_ram_ptable_init_v1
D/[0] smem ram ptable found: ver: 1 len: 5
E/[0] Failed to initialize SCM
I/[0] welcome to lk

D/[0] calling constructors
D/[0] initializing heap
D/[0] initializing threads
D/[0] initializing dpc
D/[0] initializing timers
D/[0] creating bootstrap completion thread
D/[10] top of bootstrap2()
I/[10] bootargs: 0x0 0x0 0x23400000 0x644d5241
I/[20] 0x0000000020000000-0x000000007fffffff
I/[20] 0x0000000080000000-0x00000000dfffffff
I/[20] machinetype: 65544
I/[20] cmdline=[ androidboot.emmc=true androidboot.verifiedbootstate=green androidboot.veritymode=enforcing androidboot.keymaster=1 androidboot.serialno=7fddd0c87d33 androidboot.baseband=msm mdss_mdp.panel=1:dsi:0:qcom,mdss_dsi_hx8394f_boe_720p_video:1:none:cfg:single_dsi board_id=S88537AA1:board_vol=198693]
D/[20] hello board_get_ddr_subtype
D/[20] hello smem_ram_ptable_init_v1
D/[20] smem ram ptable found: ver: 1 len: 5
I/[20] [LK]   plat=294/1 variant=8/1/0 socrev=10000 subtype=0/0/0/0 pmic_rev=<25/0/1> <17/0/2> <0/0/0> <0/0/0>
D/[20] initializing platform
I/[20] platform_init()
D/[20] initializing target
I/[20] target_init()
D/[30]  Initializing MMC host data structure and clock!
D/[40] Decoded CID fields:
D/[40] Manufacturer ID: 15
D/[40] OEM ID: 0x100
D/[40] Product Name: RX1BMB
D/[40] Product revision: 0.7
D/[40] Product serial number: [deleted]
D/[40] Manufacturing date:  [deleted]
D/[40] Decoded CSD fields:
D/[40] cmmc_structure: 3
D/[40] card_cmd_class: f5
D/[40] write_blk_len: 512
D/[40] read_blk_len: 512
D/[40] r2w_factor: 3
D/[40] sector_size: 0
D/[40] c_size_mult:7
D/[40] c_size: 4095
D/[40] nsac_clk_cycle: 100
D/[40] taac_ns: 15000000
D/[40] tran_speed: 0 kbps
D/[40] erase_blk_len: 0
D/[40] read_blk_misalign: 0
D/[40] write_blk_misalign: 0
D/[40] read_blk_partial: 0
D/[40] write_blk_partial: 0
D/[40] wp_grp_size: 16384
D/[40] Card Capacity: 31268536320 Bytes
I/[40] SDHC Running in HS400 mode
I/[50] Done initialization of the card
D/[50] erase_grpsize: 31
D/[50] erase_grpmult: 31
D/[50] wp_grpsize: 15
D/[50] wp_grpen: 1
D/[50] perm_wp: 0
D/[50] temp_wp: 0
I/[50] mbr partition table dump:
I/[50] 	0: status 0x0, type 0xee, start 0x1, len 0xffffffff
I/[50] 	1: status 0x0, type 0x0, start 0x0, len 0x0
I/[50] 	2: status 0x0, type 0x0, start 0x0, len 0x0
I/[50] 	3: status 0x0, type 0x0, start 0x0, len 0x0
I/[50] found GPT
I/[60] pm8x41_get_is_cold_boot: cold boot
I/[60] Waiting for the RPM to populate smd channel table
D/[60] calling apps_init()

However after calling apps_init() the device rebooted for unknown reasons.Still tracking.

**Comment by fxsheep** [comment]
SCM might be the problem.

**Comment by feherneoh** [comment]
I have a hunch that this problem will be DT/memory related
I had instant reboots with the NEW codebase in early stage until I patched the memory table parsing for MSM8953. Most newer bootloaders (basycally any non-8994 64bit device) pass memory data in different format than older ones do.

**Comment by fxsheep** [comment]
@feherneoh It looks so, things crashes randomly.Btw how to patch memory table parsing?And what do you refer to with NEW codebase? Thanks.

**Comment by fxsheep** [comment]
Sorry, this is mainly my mistake.EFIDroid only allow me to select msm8952 target (LA.BR branch) however msm8937 is on 8952 target with LA.UM branch, I have to modify the config by myself to get it working.
However display still crashes LK.

**Comment by fxsheep** [comment]
LK now works fine with display from DTB, though LCD looks weird.
However UEFI crashes:(reboot immediately),and here are logs dumped from ram:
the avaiable length of out_buf is not enough.
  allocating z_stream failed.
    1.2.8   header error
   inflateInit2 failed!
   uncompression error
